insert into countries values(1, 'Afghanistan');
insert into countries values(2, 'Albania');
insert into countries values(3, 'Algeria');
insert into countries values(4, 'Andorra');
insert into countries values(5, 'Angola');
insert into countries values(6, 'Antigua and Barbuda');
insert into countries values(7, 'Argentina');
insert into countries values(8, 'Armenia');
insert into countries values(9, 'Australia');
insert into countries values(10, 'Austria');
insert into countries values(11, 'Azerbaijan');
insert into countries values(12, 'Bahamas');
insert into countries values(13, 'Bahrain');
insert into countries values(14, 'Bangladesh');
insert into countries values(15, 'Barbados');
insert into countries values(16, 'Belarus');
insert into countries values(17, 'Belgium');
insert into countries values(18, 'Belize');
insert into countries values(19, 'Benin');
insert into countries values(20, 'Bhutan');
insert into countries values(21, 'Bolivia');
insert into countries values(22, 'Bosnia and Herzegovina');
insert into countries values(23, 'Botswana');
insert into countries values(24, 'Brazil');
insert into countries values(25, 'Brunei');
insert into countries values(26, 'Bulgaria');
insert into countries values(27, 'Burkina Faso');
insert into countries values(28, 'Burundi');
insert into countries values(29, E'Côte d\'Ivoire');
insert into countries values(30, 'Cabo Verde');
insert into countries values(31, 'Cambodia');
insert into countries values(32, 'Cameroon');
insert into countries values(33, 'Canada');
insert into countries values(34, 'Central African Republic');
insert into countries values(35, 'Chad');
insert into countries values(36, 'Chile');
insert into countries values(37, 'China');
insert into countries values(38, 'Colombia');
insert into countries values(39, 'Comoros');
insert into countries values(40, 'Congo (Congo-Brazzaville)');
insert into countries values(41, 'Costa Rica');
insert into countries values(42, 'Croatia');
insert into countries values(43, 'Cuba');
insert into countries values(44, 'Cyprus');
insert into countries values(45, 'Czechia (Czech Republic)');
insert into countries values(46, 'Democratic Republic of the Congo');
insert into countries values(47, 'Denmark');
insert into countries values(48, 'Djibouti');
insert into countries values(49, 'Dominica');
insert into countries values(50, 'Dominican Republic');
insert into countries values(51, 'Ecuador');
insert into countries values(52, 'Egypt');
insert into countries values(53, 'El Salvador');
insert into countries values(54, 'Equatorial Guinea');
insert into countries values(55, 'Eritrea');
insert into countries values(56, 'Estonia');
insert into countries values(57, 'Eswatini (fmr. "Swaziland")');
insert into countries values(58, 'Ethiopia');
insert into countries values(59, 'Fiji');
insert into countries values(60, 'Finland');
insert into countries values(61, 'France');
insert into countries values(62, 'Gabon');
insert into countries values(63, 'Gambia');
insert into countries values(64, 'Georgia');
insert into countries values(65, 'Germany');
insert into countries values(66, 'Ghana');
insert into countries values(67, 'Greece');
insert into countries values(68, 'Grenada');
insert into countries values(69, 'Guatemala');
insert into countries values(70, 'Guinea');
insert into countries values(71, 'Guinea-Bissau');
insert into countries values(72, 'Guyana');
insert into countries values(73, 'Haiti');
insert into countries values(74, 'Holy See');
insert into countries values(75, 'Honduras');
insert into countries values(76, 'Hungary');
insert into countries values(77, 'Iceland');
insert into countries values(78, 'India');
insert into countries values(79, 'Indonesia');
insert into countries values(80, 'Iran');
insert into countries values(81, 'Iraq');
insert into countries values(82, 'Ireland');
insert into countries values(83, 'Israel');
insert into countries values(84, 'Italy');
insert into countries values(85, 'Jamaica');
insert into countries values(86, 'Japan');
insert into countries values(87, 'Jordan');
insert into countries values(88, 'Kazakhstan');
insert into countries values(89, 'Kenya');
insert into countries values(90, 'Kiribati');
insert into countries values(91, 'Kuwait');
insert into countries values(92, 'Kyrgyzstan');
insert into countries values(93, 'Laos');
insert into countries values(94, 'Latvia');
insert into countries values(95, 'Lebanon');
insert into countries values(96, 'Lesotho');
insert into countries values(97, 'Liberia');
insert into countries values(98, 'Libya');
insert into countries values(99, 'Liechtenstein');
insert into countries values(100, 'Lithuania');
insert into countries values(101, 'Luxembourg');
insert into countries values(102, 'Madagascar');
insert into countries values(103, 'Malawi');
insert into countries values(104, 'Malaysia');
insert into countries values(105, 'Maldives');
insert into countries values(106, 'Mali');
insert into countries values(107, 'Malta');
insert into countries values(108, 'Marshall Islands');
insert into countries values(109, 'Mauritania');
insert into countries values(110, 'Mauritius');
insert into countries values(111, 'Mexico');
insert into countries values(112, 'Micronesia');
insert into countries values(113, 'Moldova');
insert into countries values(114, 'Monaco');
insert into countries values(115, 'Mongolia');
insert into countries values(116, 'Montenegro');
insert into countries values(117, 'Morocco');
insert into countries values(118, 'Mozambique');
insert into countries values(119, 'Myanmar (formerly Burma)');
insert into countries values(120, 'Namibia');
insert into countries values(121, 'Nauru');
insert into countries values(122, 'Nepal');
insert into countries values(123, 'Netherlands');
insert into countries values(124, 'New Zealand');
insert into countries values(125, 'Nicaragua');
insert into countries values(126, 'Niger');
insert into countries values(127, 'Nigeria');
insert into countries values(128, 'North Korea');
insert into countries values(129, 'North Macedonia');
insert into countries values(130, 'Norway');
insert into countries values(131, 'Oman');
insert into countries values(132, 'Pakistan');
insert into countries values(133, 'Palau');
insert into countries values(134, 'Palestine State');
insert into countries values(135, 'Panama');
insert into countries values(136, 'Papua New Guinea');
insert into countries values(137, 'Paraguay');
insert into countries values(138, 'Peru');
insert into countries values(139, 'Philippines');
insert into countries values(140, 'Poland');
insert into countries values(141, 'Portugal');
insert into countries values(142, 'Qatar');
insert into countries values(143, 'Romania');
insert into countries values(144, 'Russia');
insert into countries values(145, 'Rwanda');
insert into countries values(146, 'Saint Kitts and Nevis');
insert into countries values(147, 'Saint Lucia');
insert into countries values(148, 'Saint Vincent and the Grenadines');
insert into countries values(149, 'Samoa');
insert into countries values(150, 'San Marino');
insert into countries values(151, 'Sao Tome and Principe');
insert into countries values(152, 'Saudi Arabia');
insert into countries values(153, 'Senegal');
insert into countries values(154, 'Serbia');
insert into countries values(155, 'Seychelles');
insert into countries values(156, 'Sierra Leone');
insert into countries values(157, 'Singapore');
insert into countries values(158, 'Slovakia');
insert into countries values(159, 'Slovenia');
insert into countries values(160, 'Solomon Islands');
insert into countries values(161, 'Somalia');
insert into countries values(162, 'South Africa');
insert into countries values(163, 'South Korea');
insert into countries values(164, 'South Sudan');
insert into countries values(165, 'Spain');
insert into countries values(166, 'Sri Lanka');
insert into countries values(167, 'Sudan');
insert into countries values(168, 'Suriname');
insert into countries values(169, 'Sweden');
insert into countries values(170, 'Switzerland');
insert into countries values(171, 'Syria');
insert into countries values(172, 'Tajikistan');
insert into countries values(173, 'Tanzania');
insert into countries values(174, 'Thailand');
insert into countries values(175, 'Timor-Leste');
insert into countries values(176, 'Togo');
insert into countries values(177, 'Tonga');
insert into countries values(178, 'Trinidad and Tobago');
insert into countries values(179, 'Tunisia');
insert into countries values(180, 'Turkey');
insert into countries values(181, 'Turkmenistan');
insert into countries values(182, 'Tuvalu');
insert into countries values(183, 'Uganda');
insert into countries values(184, 'Ukraine');
insert into countries values(185, 'United Arab Emirates');
insert into countries values(186, 'United Kingdom');
insert into countries values(187, 'United States of America');
insert into countries values(188, 'Uruguay');
insert into countries values(189, 'Uzbekistan');
insert into countries values(190, 'Vanuatu');
insert into countries values(191, 'Venezuela');
insert into countries values(192, 'Vietnam');
insert into countries values(193, 'Yemen');
insert into countries values(194, 'Zambia');
insert into countries values(195, 'Zimbabwe');
